"""empty message

Revision ID: 607feb6387fa
Revises: fda2ebe866f2
Create Date: 2022-10-21 17:27:42.078460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607feb6387fa'
down_revision = 'fda2ebe866f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_data', sa.Column('empid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_data', 'empid')
    # ### end Alembic commands ###
