"""empty message

Revision ID: fda2ebe866f2
Revises: d4ec6981315c
Create Date: 2022-10-19 23:09:17.724469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda2ebe866f2'
down_revision = 'd4ec6981315c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_data',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('ename', sa.String(length=20), nullable=False),
    sa.Column('edesignation', sa.String(length=20), nullable=True),
    sa.Column('ecnum', sa.Integer(), nullable=True),
    sa.Column('efname', sa.String(length=20), nullable=True),
    sa.Column('emname', sa.String(length=20), nullable=True),
    sa.Column('eenum', sa.String(length=20), nullable=True),
    sa.Column('enid', sa.Integer(), nullable=True),
    sa.Column('paddr', sa.String(), nullable=True),
    sa.Column('edob', sa.String(length=20), nullable=True),
    sa.Column('epaddress', sa.String(), nullable=True),
    sa.Column('eedu', sa.String(), nullable=True),
    sa.Column('ejobinfo', sa.String(), nullable=True),
    sa.Column('ephoto', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_data')
    # ### end Alembic commands ###
